### PR TITLE
Fixed Command Injection Vulnerability

### PR DESCRIPTION
**Pull request by mufeedvh**
:gear:  **Fix:**

Escaping characters that can execute shell commands can mitigate this vulnerability. The `escapeShell()` function replaces characters that can lead to this vulnerability.

:question: **How:**

The fix is simple, it escapes characters that can be used to concatenate another shell command.

<hr>

### :v: **Fixed!**

<hr>

### CODE REVIEW

**Review by toufik-airane — CHANGES_REQUESTED** [review]
Hello, 👋 

🚫 The contribution doesn't seem to apply all the requirements.

- **Security sanitization should be done immediately after a variable assignation.**
I recommend reusing the declared variable `command` and immediately filter bad characters.

- **Command injection mitigation has to escape bad characters, such as:**
; (semi-colon)
| (pipe)
$ (dollar)
` (acute accent)

Thanks for your attention. 😌

**Review by JamieSlome — COMMENTED** [review]
Thank you for your submission @mufeedvh! Please comment your thoughts on the suggested changes by @toufik-airane! 🍰

**Comment by mufeedvh** [comment]
Hello,

As @toufik-airane said, the initial commit of this pull request didn't fit all the requirements. I have made changes to all the suggested requirements in the new commit (https://github.com/418sec/node-df/pull/1/commits/c3ff11676f1241ca71101dfc948912bcd89346e1).

:question: **How:**

The new fix uses `execFile()` instead of `exec()` to mitigate this vulnerability.

:books: **Reference:**

- https://www.hacksplaining.com/prevention/command-execution
- https://stackoverflow.com/questions/32566389/how-do-i-escape-command-injection-in-node-child-process
- https://gist.github.com/evilpacket/5a9655c752982faf7c4ec6450c1cbf1b
- https://hackernoon.com/nodejs-security-issue-javascript-node-example-tutorial-vulnerabilities-hack-line-url-command-injection-412011924d1b

**Comment by toufik-airane** [comment]
Dear @mufeedvh,

I was thinking about filtering `options.file` to delete the bad characters mentioned before.

**Review by toufik-airane — CHANGES_REQUESTED** [review]
Dear @mufeedvh,

I was thinking about sanitizing the `options.file` input to filter the bad characters.

**Comment by mufeedvh** [comment]
Yeah, that's a good idea too but as per the Internet's recommendations/suggestions, this fix seemed to be more effective. Let me know if this new commit fails to fit any requirements.

**Comment by toufik-airane** [comment]
LGTM.  ✅

After further testing, I definitely agree on the safety of the fix.
Thank you for your contribution. 🏆

**Review by toufik-airane — APPROVED** [review]
LGTM. ✅

After further testing, I definitely agree on the safety of the fix.
Thank you for your contribution. 🏆

**Comment by huntr-helper** [comment]
Congratulations @mufeedvh - you are the successful huntr!
Thank you for submitting your fix - we have approved your pull request and will merge your commits into our master branch. 
If you have any questions, please respond in the comments section. Your bounty is on its way - keep hunting.

**Pull request merged**
